

#region license

/// <License>
/// <FileLabel>BearcatSoft(R) Library</FileLabel>
/// <Copyrights>Copyright (C) 2003 - 2004, BearcatSoft(R). All rights reserved.
/// The software and associated documentation supplied hereunder 
/// are the proprietary information of BearcatSoft(R) and are supplied 
/// subject to licence terms.
/// </Copyrights>
/// <Product>This file was generated by BearcatSoft Genarator(R)</Product>
/// <LicenseDetails>http://BearcatSoft.no-ip.com/GeneratorLicense</LicenseDetails>
/// <LicenseDetails2>http://www.BearcatSoft.com/GeneratorLicense</LicenseDetails2>
/// <Contact>http://BearcatSoft.no-ip.com</Contact>
/// <Contact2>http://www.BearcatSoft.com</Contact2>
/// <Company>BearcatSoft(R)</Company>
/// <Trademarks>BearcatSoft(R), BearcatSoft Generator(R) are a registered trademarks of BearcatSoft company</Trademarks>
/// </License>
/// 
#endregion

#region usings

using System;
using System.Collections.Specialized ;

using BearcatSoft.BSGen.Framework;
using BearcatSoft.BSGen.Framework.Components.CBSGFieldItem;
using BearcatSoft.BSGen.Framework.Components.CBSGFieldItemGroup;
using BearcatSoft.BSGen.Framework.Components.CBSGClass ;
using BearcatSoft.BSGen.Framework.Components.CBSGTemplate;
using BearcatSoft.BSGen.Framework.Components.CBSGView ;
using BearcatSoft.BSGen.Framework.Components.CBSGForeignField ;
using BearcatSoft.BSGen.Framework.Components.CBSGForeignFieldGroup ;

using BearcatSoft.BSGen.Engine.Classes.FieldsHelpers;
using BearcatSoft.BSGen.Engine.Generator.Components ;
using BearcatSoft.BSGen.Engine.Classes.ModelHelpers ;
using BearcatSoft.BSGen.EngineF35.Generator.DataAccessProjects.BSGA.Components.DAL.Providers;
#endregion




namespace BearcatSoft.BSGen.EngineF35.Generator.oraclejee_mvc.src.main.java.com.sprhib.dao
{	

	[GenerateANDCondition(new string[]{"GENER_LIB_DATAACCESS_DATAACCESS"})]
    [BSGTemplate(typeof(BSGClass), SourceCodeType.JSP_SourceCodeType
        , @"oraclejee-mvc\src\main\webapp\WEB-INF\pages\")]
    public class BSG_OracleJEE_add_form : ProxyBaseClass
	{

        #region protected override Generate functions

		protected override void GenerateSourceForModel(BearcatSoft.BSGen.Framework.Components.CBSGModel.BSGModel item, BSGSourceFile src)
		{
		}

        protected override void GenerateSource(
            BSGClass item
            , BSGSourceFile src)
        {
            BearcatSoft.BSGen.Framework.Components.CBSGCLSType.BSGCLSType.BSGCLSType_Modified = "java";
            

            this.InitializeGenerator(
                item
                , src
                , ModelForGenerator);

            src.FileName = "add-" + this.IBSBSGClass.MHIBSNameLowerCase + @"-form";

            this.IBSBSGClass.SetChoosedDataSet_First();

            this.gener_header();
            this.gener_fields();
            this.gener_footer();

        }

        public void gener_header()
        {
            this.Src.AddLn(@"<%@taglib uri=" + PP() + @"http://www.oraclejeeframework.org/tags/form" + PP() + @" prefix=" + PP() + @"form" + PP() + @" %>

<?xml version=" + PP() + @"1.0" + PP() + @" encoding=" + PP() + @"ISO-8859-1" + PP() + @" ?>

<%@ page language=" + PP() + @"java" + PP() + @" contentType=" + PP() + @"text/html; charset=ISO-8859-1" + PP() + @"
    pageEncoding=" + PP() + @"ISO-8859-1" + PP() + @"%>
    
<!DOCTYPE html PUBLIC " + PP() + @"-//W3C//DTD XHTML 1.0 Transitional//EN" + PP() + @" " + PP() + @"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" + PP() + @">
<html xmlns=" + PP() + @"http://www.w3.org/1999/xhtml" + PP() + @">
<head>
<meta http-equiv=" + PP() + @"Content-Type" + PP() + @" content=" + PP() + @"text/html; charset=ISO-8859-1" + PP() + @" />
<title>Add " + this.IBSBSGClass.MHIBSNameJavaCase + @" page</title>
</head>
<body>
<h1>Add " + this.IBSBSGClass.MHIBSNameJavaCase + @" page</h1>
<p>Here you can add a new " + this.IBSBSGClass.MHIBSNameJavaCase + @".</p>
");

            this.Src.AddLn(@"
<form:form method=" + PP() + @"POST" + PP() + @" commandName=" + PP() + @"" + this.IBSBSGClass.MHIBSNameJavaCase + @"" + PP() + @" action=" + PP() + @"${pageContext.request.contextPath}/" + this.IBSBSGClass.MHIBSNameLowerCase + @"/add.html" + PP() + @">
");

            this.Src.AddLn(@"
<table>
");

            this.Src.AddLn(@"<tbody>");
        }

        public void gener_footer()
        {
            this.Src.AddLn(@"
</tbody>
</table>
</form:form>

<p><a href=" + PP() + @"${pageContext.request.contextPath}/index.html" + PP() + @">Home page</a></p>
</body>
</html>
");

        }

        public void gener_fields()
        {
            
            foreach (BSGFieldItem dd_fi in this.IBSBSGClass.MHIBSChoosedDataSet.ClassFields)
            {


                string c_type = dd_fi.PBSGFINetType.PBSGNTCLSType.BSGCLSType_ClsTypeConverted();
                    this.Src.AddLn(@"
	<tr>
		<td>" + dd_fi.Name + @":</td>
		<td><form:input path=" + PP() + @"" + dd_fi.Name + @"" + PP() + @" /></td>
	</tr>
");

            }

            this.Src.AddLn(@"
    <tr>
		<td><input type=" + PP() + @"submit" + PP() + @" value=" + PP() + @"Add" + PP() + @" /></td>
		<td></td>
	</tr>
");
        }

        public static string PP()
        {
            return @"""";
        }
		#endregion

	}
 
}
