

#region license

/// <License>
/// <FileLabel>BearcatSoft(R) Library</FileLabel>
/// <Copyrights>Copyright (C) 2003 - 2004, BearcatSoft(R). All rights reserved.
/// The software and associated documentation supplied hereunder 
/// are the proprietary information of BearcatSoft(R) and are supplied 
/// subject to licence terms.
/// </Copyrights>
/// <Product>This file was generated by BearcatSoft Genarator(R)</Product>
/// <LicenseDetails>http://BearcatSoft.no-ip.com/GeneratorLicense</LicenseDetails>
/// <LicenseDetails2>http://www.BearcatSoft.com/GeneratorLicense</LicenseDetails2>
/// <Contact>http://BearcatSoft.no-ip.com</Contact>
/// <Contact2>http://www.BearcatSoft.com</Contact2>
/// <Company>BearcatSoft(R)</Company>
/// <Trademarks>BearcatSoft(R), BearcatSoft Generator(R) are a registered trademarks of BearcatSoft company</Trademarks>
/// </License>
/// 
#endregion

#region usings

using System;
using System.Collections.Specialized ;

using BearcatSoft.BSGen.Framework;
using BearcatSoft.BSGen.Framework.Components.CBSGFieldItem;
using BearcatSoft.BSGen.Framework.Components.CBSGFieldItemGroup;
using BearcatSoft.BSGen.Framework.Components.CBSGClass ;
using BearcatSoft.BSGen.Framework.Components.CBSGTemplate;
using BearcatSoft.BSGen.Framework.Components.CBSGView ;
using BearcatSoft.BSGen.Framework.Components.CBSGForeignField ;
using BearcatSoft.BSGen.Framework.Components.CBSGForeignFieldGroup ;

using BearcatSoft.BSGen.Engine.Classes.FieldsHelpers;
using BearcatSoft.BSGen.Engine.Generator.Components ;
using BearcatSoft.BSGen.Engine.Classes.ModelHelpers ;
using BearcatSoft.BSGen.EngineF35.Generator.DataAccessProjects.BSGA.Components.DAL.Providers;

using BearcatSoft.BSGen.Framework.Components.CBSGModel;

#endregion




namespace BearcatSoft.BSGen.EngineF35.Generator.oraclejee_mvc.src.main.java.com.sprhib.dao
{	

	[GenerateANDCondition(new string[]{"GENER_LIB_DATAACCESS_DATAACCESS"})]
    [BSGTemplate(typeof(BSGModel)
        , SourceCodeType.JSP_SourceCodeType
        , @"oraclejee-mvc\src\main\webapp\WEB-INF\pages\gen")]
    public class BSG_OracleJEE_home_form : BSGTemplate
    {

        #region fields
        BSGSourceFile _src = null;
        public BSGSourceFile Src
        {
            get { return _src; }
        }

        IBSModel _model = null;
        public IBSModel IBSModel
        {
            get { return _model; }
        }

        private SettingsOfGeneration _sog = null;
        public SettingsOfGeneration SOG
        {
            get { return this._sog; }
        }

        BearcatSoft.BSGen.Framework.Components.CBSGModel.BSGModelCollection _modelNamespacesCollection;
        #endregion

        public void InitializeObjects(
            BSGModel item
            , BSGSourceFile src)
        {
            this._src = src;
            this._model = new IBSModel(item);
            this._sog = new SettingsOfGeneration(this.ModelForGenerator);
            this._modelNamespacesCollection = this.PGenerData.ModelNamespaces;
        }

        #region protected override Generate functions

		protected override void GenerateSourceForModel(
            BearcatSoft.BSGen.Framework.Components.CBSGModel.BSGModel item
            , BSGSourceFile src)
		{
            BearcatSoft.BSGen.Framework.Components.CBSGCLSType.BSGCLSType.BSGCLSType_Modified = "java";

            this.InitializeObjects(item, src);
            this.Src.FileName = "gen_home";
            this.Src.AddLn(@"
<?xml version=" + PP() + @"1.0" + PP() + @" encoding=" + PP() + @"ISO-8859-1" + PP() + @" ?>
<%@ page language=" + PP() + @"java" + PP() + @" contentType=" + PP() + @"text/html; charset=ISO-8859-1" + PP() + @"
    pageEncoding=" + PP() + @"ISO-8859-1" + PP() + @"%>
<!DOCTYPE html PUBLIC " + PP() + @"-//W3C//DTD XHTML 1.0 Transitional//EN" + PP() + @" " + PP() + @"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" + PP() + @">
<html xmlns=" + PP() + @"http://www.w3.org/1999/xhtml" + PP() + @">
<head>
<meta http-equiv=" + PP() + @"Content-Type" + PP() + @" content=" + PP() + @"text/html; charset=ISO-8859-1" + PP() + @" />
<title>Home page</title>
</head>
<body>
<h1>Home page</h1>
<p>
${message}<br/>");

            foreach (BSGClass  dd in this.IBSModel.MX.Items)
            {

                IBSBSGClass ddc = new IBSBSGClass(dd
                    , this.IBSModel.MX
                    , BSGClass.DEFAULT_ALL_DATASETS);

                ddc.SetChoosedDataSet_First();

                this.Src.AddLn(@"
<a href=" 
                    + PP() + @"${pageContext.request.contextPath}/" 
                    + ddc.MHIBSNameLowerCase + @"/add.html" + PP()          
                    + @">Add new " + ddc.MHIBSNameLowerCase + @"</a><br/>
");

                this.Src.AddLn(@"<a href=" + PP() + @"${pageContext.request.contextPath}/" 
                    + ddc.MHIBSNameLowerCase + @"/list.html" + PP() + @"> " 
                    + ddc.MHIBSNameLowerCase + @"</a><br/>
");

            }


            this.Src.AddLn(@"</p>
</body>
</html>

                ");
		}

        protected override void GenerateSource(
            BSGClass item
            , BSGSourceFile src)
        {

        }

        public void add_fixed()
        {
            this.Src.AddLn(@"
<a href=" + PP() + @"${pageContext.request.contextPath}/team/add.html" + PP() + @">Add new team</a><br/>
<a href=" + PP() + @"${pageContext.request.contextPath}/team/list.html" + PP() + @">Team list</a><br/>
<a href=" + PP() + @"${pageContext.request.contextPath}/team/list-2.html" + PP() + @">Team list-2</a><br/>
<a href=" + PP() + @"${pageContext.request.contextPath}/customer/add.html" + PP() + @">Add new customer</a><br/>
<a href=" + PP() + @"${pageContext.request.contextPath}/customer/list.html" + PP() + @">customer list</a><br/>
<a href=" + PP() + @"${pageContext.request.contextPath}/joo2_virtuemart_ept_customvalues/list.html" + PP() + @">joo2_virtuemart_ept_customvalues list</a><br/>
<a href=" + PP() + @"${pageContext.request.contextPath}/joo2_virtuemart_ept_customvalues/add.html" + PP() + @">joo2_virtuemart_ept_customvalues add</a><br/>
");

        }
        public static string PP()
        {
            return @"""";
        }
		#endregion

	}
 
}
