

#region license

/// <License>
/// <FileLabel>BearcatSoft(R) Library</FileLabel>
/// <Copyrights>Copyright (C) 2003 - 2004, BearcatSoft(R). All rights reserved.
/// The software and associated documentation supplied hereunder 
/// are the proprietary information of BearcatSoft(R) and are supplied 
/// subject to licence terms.
/// </Copyrights>
/// <Product>This file was generated by BearcatSoft Genarator(R)</Product>
/// <LicenseDetails>http://BearcatSoft.no-ip.com/GeneratorLicense</LicenseDetails>
/// <LicenseDetails2>http://www.BearcatSoft.com/GeneratorLicense</LicenseDetails2>
/// <Contact>http://BearcatSoft.no-ip.com</Contact>
/// <Contact2>http://www.BearcatSoft.com</Contact2>
/// <Company>BearcatSoft(R)</Company>
/// <Trademarks>BearcatSoft(R), BearcatSoft Generator(R) are a registered trademarks of BearcatSoft company</Trademarks>
/// </License>
/// 
#endregion

#region usings

using System;
using System.Collections.Specialized ;

using BearcatSoft.BSGen.Framework;
using BearcatSoft.BSGen.Framework.Components.CBSGFieldItem;
using BearcatSoft.BSGen.Framework.Components.CBSGFieldItemGroup;
using BearcatSoft.BSGen.Framework.Components.CBSGClass ;
using BearcatSoft.BSGen.Framework.Components.CBSGTemplate;
using BearcatSoft.BSGen.Framework.Components.CBSGView ;
using BearcatSoft.BSGen.Framework.Components.CBSGForeignField ;
using BearcatSoft.BSGen.Framework.Components.CBSGForeignFieldGroup ;

using BearcatSoft.BSGen.Engine.Classes.FieldsHelpers;
using BearcatSoft.BSGen.Engine.Generator.Components ;
using BearcatSoft.BSGen.Engine.Classes.ModelHelpers ;
using BearcatSoft.BSGen.EngineF35.Generator.DataAccessProjects.BSGA.Components.DAL.Providers;
#endregion




namespace BearcatSoft.BSGen.EngineF35.Generator.oraclejee_mvc.src.main.java.com.sprhib.dao
{	
	[GenerateANDCondition(new string[]{"GENER_LIB_DATAACCESS_DATAACCESS"})]
    [BSGTemplate(typeof(BSGClass), SourceCodeType.Java_SourceCodeType, @"oraclejee-mvc\src\main\java\com\sprhib\dao\")]
    public class BSG_OracleJEE_DAO_Implementation : ProxyBaseClass
	{


        #region protected override Generate functions

		protected override void GenerateSourceForModel(BearcatSoft.BSGen.Framework.Components.CBSGModel.BSGModel item, BSGSourceFile src)
		{
		}

		protected override void GenerateSource(
            BSGClass item
            , BSGSourceFile src)
		{
            BearcatSoft.BSGen.Framework.Components.CBSGCLSType.BSGCLSType.BSGCLSType_Modified = "java";
            this.InitializeGenerator(
                item
                , src
                , ModelForGenerator);

            src.FileName = "" + this.IBSBSGClass.MHIBSNameJavaCase + @"DAOImpl";

            this.IBSBSGClass.SetChoosedDataSet_First();
 
            this.Src.AddLn(@"
package com.sprhib.dao;");

            this.Src.AddLn(@"

import java.util.List;");

            this.Src.AddLn(@"

import org.hibernate.Session;");

            this.Src.AddLn(@"
import org.hibernate.SessionFactory;");

            this.Src.AddLn(@"
import org.oraclejeeframework.beans.factory.annotation.Autowired;");

            this.Src.AddLn(@"
import org.oraclejeeframework.stereotype.Repository;
");

            this.Src.AddLn(@"
import com.sprhib.model." + this.IBSBSGClass.MHIBSNameJavaCase + @";
");

            this.Src.AddLn(@"
@Repository
public class " + this.IBSBSGClass.MHIBSNameJavaCase + @"DAOImpl implements " + this.IBSBSGClass.MHIBSNameJavaCase + @"DAO {
");

            this.Src.AddLn(@"	
	@Autowired
	private SessionFactory sessionFactory;
");

            this.Src.AddLn(@"	
	private Session getCurrentSession() {");

            this.Src.AddLn(@"
		return sessionFactory.getCurrentSession();");

            this.Src.AddLn(@"
	}
");

            this.Src.AddLn(@"
	public void add" + this.IBSBSGClass.MHIBSNameJavaCase + @"(" + this.IBSBSGClass.MHIBSNameJavaCase + @" " + this.IBSBSGClass.MHIBSNameJavaCase + @") {
		");

            this.Src.AddLn(@"getCurrentSession().save(" + this.IBSBSGClass.MHIBSNameJavaCase + @");
	}");

            this.Src.AddLn(@"
");

            this.Src.AddLn(@"
	public void update" + this.IBSBSGClass.MHIBSNameJavaCase + @"(" + this.IBSBSGClass.MHIBSNameJavaCase + @" " + this.IBSBSGClass.MHIBSNameJavaCase + @") {");

            foreach (BSGFieldItem dd_fi in this.IBSBSGClass.MHIBSChoosedDataSet.ClassFields)
            {

                this.Src.AddLn(@"
		" + this.IBSBSGClass.MHIBSNameJavaCase + @" " + this.IBSBSGClass.MHIBSNameJavaCase + @"ToUpdate = get" + this.IBSBSGClass.MHIBSNameJavaCase + @"(" + this.IBSBSGClass.MHIBSNameJavaCase + @".get" + dd_fi.Name + @"());");
                break;

            }
            int ii_id = 0;

            foreach (BSGFieldItem dd_fi in this.IBSBSGClass.MHIBSChoosedDataSet.ClassFields)
            {

                if (ii_id > 0)
                {
                    this.Src.AddLn(@"
		" + this.IBSBSGClass.MHIBSNameJavaCase + @"ToUpdate.set" + dd_fi.Name + @"(" + this.IBSBSGClass.MHIBSNameJavaCase + @".get" + dd_fi.Name + @"());");
                }

                ii_id++;
            }


            this.Src.AddLn(@"
		getCurrentSession().update(" + this.IBSBSGClass.MHIBSNameJavaCase + @"ToUpdate);
		
	}");

            this.Src.AddLn(@"
");

            this.Src.AddLn(@"
	public " + this.IBSBSGClass.MHIBSNameJavaCase + @" get" + this.IBSBSGClass.MHIBSNameJavaCase
             + @"(" +  this.IBSBSGClass.GePrimaryType_Str()  + @" id) {
");

            this.Src.AddLn(@"
		" + this.IBSBSGClass.MHIBSNameJavaCase + @" " + this.IBSBSGClass.MHIBSNameJavaCase + @" = (" + this.IBSBSGClass.MHIBSNameJavaCase + @") getCurrentSession().get(" + this.IBSBSGClass.MHIBSNameJavaCase + @".class, id);
		return " + this.IBSBSGClass.MHIBSNameJavaCase + @";
	}");

            this.Src.AddLn(@"
");

            this.Src.AddLn(@"
	public void delete" + this.IBSBSGClass.MHIBSNameJavaCase + @"(" + this.IBSBSGClass.GePrimaryType_Str() + @" id) {
		" + this.IBSBSGClass.MHIBSNameJavaCase + @" " + this.IBSBSGClass.MHIBSNameJavaCase + @" = get" + this.IBSBSGClass.MHIBSNameJavaCase + @"(id);
");

            this.Src.AddLn(@"
		if (" + this.IBSBSGClass.MHIBSNameJavaCase + @" != null)");

            this.Src.AddLn(@"
			getCurrentSession().delete(" + this.IBSBSGClass.MHIBSNameJavaCase + @");
	}");

            this.Src.AddLn(@"
");

            this.Src.AddLn(@"
	@SuppressWarnings(" + PP() + @"unchecked" + PP() + @")");

            this.Src.AddLn(@"
	public List<" + this.IBSBSGClass.MHIBSNameJavaCase + @"> get" + this.IBSBSGClass.MHIBSNameJavaCase + @"s() {");

            this.Src.AddLn(@"
		return getCurrentSession().createQuery(" + PP() + @"from " + this.IBSBSGClass.MHIBSNameJavaCase + @"" + PP() + @").list();
	}
");

            this.Src.AddLn(@"
}
");
		}

        public static string PP()
        {
            return @"""";
        }
		#endregion

	}
 
}
